using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Script.Serialization;

namespace Inzynierka.Models
{
    public enum nationality
    {
                    Afghan,
                    Albanian,
                    Algerian,
                    American ,
                    Andorran ,  
                    Angolan ,
                    Antiguans ,
Argentinean ,
Armenian ,
Australian ,
Austrian ,
Azerbaijani ,
Bahamian ,
Bahraini ,
Bangladeshi ,
Barbadian ,
Barbudans ,
Batswana ,
Belarusian ,
Belgian ,
Belizean ,
Beninese ,
Bhutanese ,
Bolivian ,
Bosnian ,
Brazilian ,
British ,
Bruneian ,
Bulgarian ,
Burkinabe ,
Burmese ,
Burundian ,
Cambodian ,
Cameroonian ,
Canadian ,
Chadian ,
Chilean ,
Chinese ,
Colombian ,
Comoran ,
Congolese ,
CostaRican,
Croatian ,
Cuban ,
Cypriot ,
Czech ,
Danish ,
Djibouti ,
Dominican ,
Dutch ,
EastTimorese,
Ecuadorean ,
Egyptian ,
Emirian ,
Eritrean ,
Estonian ,
Ethiopian ,
Fijian ,
Filipino ,
Finnish ,
French ,
Gabonese ,
Gambian ,
Georgian ,
German ,
Ghanaian ,
Greek ,
Grenadian ,
Guatemalan ,
Bissauan ,
Guinean ,
Guyanese ,
Haitian ,
Herzegovinian ,
Honduran ,
Hungarian ,
Icelander ,
Indian ,
Indonesian ,
Iranian ,
Iraqi ,
Irish ,
Israeli ,
Italian ,
Ivorian ,
Jamaican ,
Japanese ,
Jordanian ,
Kazakhstani ,
Kenyan ,
Kittian,
Nevisian,
Kuwaiti ,
Kyrgyz ,
Laotian ,
Latvian ,
Lebanese ,
Liberian ,
Libyan ,
Liechtensteiner ,
Lithuanian ,
Luxembourger ,
Macedonian ,
Malagasy ,
Malawian ,
Malaysian ,
Maldivan ,
Malian ,
Maltese ,
Marshallese ,
Mauritanian ,
Mauritian ,
Mexican ,
Micronesian ,
Moldovan ,
Monacan ,
Mongolian ,
Moroccan ,
Mosotho ,
Motswana ,
Mozambican ,
Namibian ,
Nauruan ,
Nepalese ,
NewZealander,
NiVanuatu ,
Nicaraguan ,
Nigerien ,
NorthKorean ,
NorthernIrish ,
Norwegian ,
Omani ,
Pakistani ,
Palauan ,
Panamanian ,
Paraguayan ,
Peruvian ,
Polish ,
Portuguese ,
Qatari ,
Romanian ,
Russian ,
Rwandan ,
SaintLucian,
Salvadoran ,
Samoan ,
SanMarinese ,
SaoTomean ,
Saudi ,
Scottish ,
Senegalese ,
Serbian ,
Seychellois ,
SierraLeonean ,
Singaporean ,
Slovakian ,
Slovenian ,
SolomonIslander ,
Somali ,
SouthAfrican ,
SouthKorean ,
Spanish ,
SriLankan ,
Sudanese ,
Surinamer ,
Swazi ,
Swedish ,
Swiss ,
Syrian ,
Taiwanese ,
Tajik ,
Tanzanian ,
Thai ,
Togolese ,
Tongan ,
Tunisian ,
Turkish ,
Tuvaluan ,
Ugandan ,
Ukrainian ,
Uruguayan ,
Uzbekistani ,
Venezuelan ,
Vietnamese ,
Welsh ,
Yemenite ,
Zambian ,
Zimbabwean 
    }
    public class User
    {
        public long ID { get; set; }
        [Display(Name = "Email")]
        public String Email { get; set; }
        [Display(Name = "Imie")]
        [Required]
        [StringLength(30, ErrorMessage = "Długość {0} musi wynosić co najmniej {2} znaków.", MinimumLength = 4)]
        public String ForName { get; set; }
        [Display(Name = "Nazwisko")]
        [Required]
        [StringLength(300, ErrorMessage = "Długość {0} musi wynosić co najmniej {2} znaków.", MinimumLength = 3)]
        public String SurName { get; set; }
        [Display(Name = "Zdjecie")]
        public String Photo { get; set; }
        [Display(Name = "Telefon")]
        public long Phone { get; set; }
        [Display(Name = "Narodowość")]
        public nationality Nationality { get; set; }
        public virtual ICollection<Expo> Expo { get; set; }
    }
}